export default {
  SET_CATEGORY: 'SET_CATEGORY',
  SET_IS_ONGOING: 'SET_IS_ONGOING',
  SET_TITLE: 'SET_TITLE',
  SET_CHALLENGE_PERIOD: 'SET_CHALLENGE_PERIOD',
  SET_START_AT: 'SET_START_AT',
  SET_REFEREE: 'SET_REFEREE',
  SET_CHECKING_PERIOD: 'SET_CHECKING_PERIOD',
  SET_AMOUNT: 'SET_AMOUNT',
  SET_RECEIPIENT: 'SET_RECEIPIENT',
  SET_SLOGAN: 'SET_SLOGAN',
  RESET_CHALLENGE: 'RESET_CHALLENGE',
};
